name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            salinterpret/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('salinterpret/buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: salinterpret
          buildozer_version: stable

      # This step just lists the files to verify what was created
      - name: List created files
        run: |
          echo "Files in salinterpret/bin:"
          find salinterpret/bin -type f || echo "No files found"
          
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: salinterpret/bin/*.apk
