name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04  # Explicitly use Ubuntu 20.04 which has better compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          
          # libltinfo5 is not available, use libncurses5 instead
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libncurses5 \
            cmake \
            libffi-dev \
            libssl-dev
          
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 virtualenv buildozer==1.5.0
      
      - name: Check project structure
        run: |
          ls -la
          echo "===== Python files ====="
          find . -name "*.py" | sort
          echo "===== Buildozer spec ====="
          find . -name "buildozer.spec" | sort
      
      - name: Build APK
        run: |
          # First, determine if we need to CD into a directory
          SPEC_PATH=$(find . -name "buildozer.spec" | head -n 1)
          if [ -n "$SPEC_PATH" ]; then
            SPEC_DIR=$(dirname "$SPEC_PATH")
            echo "Found buildozer.spec in: $SPEC_DIR"
            cd "$SPEC_DIR"
          else
            echo "Error: buildozer.spec not found!"
            exit 1
          fi
          
          # Build with verbose output
          buildozer -v android debug
      
      - name: List APK files
        if: always()  # Run even if previous step fails
        run: |
          echo "Looking for APK files..."
          find . -name "*.apk"
