name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            salinterpret/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('salinterpret/buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: salinterpret
          buildozer_version: stable
          
      # Let's skip the artifact upload for now since it's causing issues
      # We'll focus on just getting a successful build first
      
      # After build completes, create a custom release without using the actions
      - name: Create GitHub Release
        if: success()
        run: |
          APK_PATH=$(find salinterpret/bin -name "*.apk" | head -n 1)
          if [ -n "$APK_PATH" ]; then
            echo "APK found at: $APK_PATH"
            
            # Install GitHub CLI
            sudo apt-get update
            sudo apt-get install -y gh
            
            # Create release with found APK
            gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
            gh release create release-v1.0 "$APK_PATH" --title "ASL Translator APK" --notes "Built with GitHub Actions"
          else
            echo "No APK file was found!"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
