name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
          
          pip install --upgrade pip
          pip install buildozer==1.5.0 Cython==0.29.33
      
      - name: Prepare project
        run: |
          echo "Preparing project structure..."
          mkdir -p myapp
          
          # Copy main.py and other files to myapp directory
          if [ -f "main.py" ]; then
            cp main.py myapp/
            cp -r *.py myapp/ || true
            cp -r assets myapp/ || true
          elif [ -f "salinterpret/main.py" ]; then
            cp salinterpret/main.py myapp/
            cp -r salinterpret/*.py myapp/ || true
            cp -r salinterpret/assets myapp/ || true
          else
            find . -type f -name "*.py" | head -5
            echo "Could not locate main.py file!"
            exit 1
          fi
          
          # Create a minimal buildozer.spec file
          cd myapp
          echo '[app]' > buildozer.spec
          echo 'title = ASL Translator' >> buildozer.spec
          echo 'package.name = asltranslator' >> buildozer.spec
          echo 'package.domain = org.test' >> buildozer.spec
          echo 'source.dir = .' >> buildozer.spec
          echo 'source.include_exts = py,png,jpg,kv,atlas' >> buildozer.spec
          echo 'version = 0.1' >> buildozer.spec
          echo 'requirements = python3,kivy==2.1.0,pillow,numpy,opencv-python-headless<4.3,requests' >> buildozer.spec
          echo 'orientation = portrait' >> buildozer.spec
          echo 'osx.python_version = 3' >> buildozer.spec
          echo 'osx.kivy_version = 2.1.0' >> buildozer.spec
          echo 'fullscreen = 0' >> buildozer.spec
          echo 'android.archs = arm64-v8a' >> buildozer.spec
          echo 'android.allow_backup = True' >> buildozer.spec
          echo 'android.permissions = CAMERA,INTERNET' >> buildozer.spec
          echo 'android.api = 31' >> buildozer.spec
          echo 'android.minapi = 21' >> buildozer.spec
          echo 'android.ndk = 23b' >> buildozer.spec
      
      - name: Build APK
        run: |
          cd myapp
          buildozer android debug
          
          # Copy APK to workspace root for easier access
          find . -name "*.apk" -exec cp {} .. \;
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: asl-translator-apk
          path: myapp/bin/*.apk
          if-no-files-found: error
